name: Lit Publish (using an action)

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run publish action
        uses: ./.github/actions/lit-publish-action
        with:
          lit-key: invalidkey

      - name: Done.
        run: echo "Done."
